name: InvestorCraft
version: 1.0
main: io.sshh.investorcraft.InvestorCraft
description: Investing in Minecraft
depend: [Vault]

commands:
    invest:
        usage: |
            /<command> : Shows Help.
            /<command> <buy/sell> <symbol> <amt> : Buy/Sell stock.
            /<command> price <symbol> : Check stock price.
            /<command> list : View owned stocks.
        description: Invest.